In [345]:
import numpy
import pandas as pd
import yfinance as yf

In [346]:
df = yf.download("ADBE", start="2021-07-12", end="2021-08-12", interval="1d")

[*********************100%***********************]  1 of 1 completed

In [347]:
df['ClosePrev'] = df['Close'].shift(1)

In [348]:
num_stocks = 10
df['Prof'] = df['Open']-df['ClosePrev']
df['actual'] = num_stocks*df['Prof']
df['isHighMoreThanClose'] = df['High'] > df['ClosePrev']
df['best'] = num_stocks*(df['High'] - df['ClosePrev'])
df['worked'] = df['isHighMoreThanClose'] | (df['Prof'] > 0)
df

,Open,High,Low,Close,Adj Close,Volume,ClosePrev,Prof,actual,isHighMoreThanClose,best,worked
Date,,,,,,,,,,,,
2021-07-12,606.000000,607.419983,596.479980,600.200012,600.200012,1696200,NaN,NaN,NaN,False,NaN,False
2021-07-13,600.559998,609.330017,598.419983,605.010010,605.010010,1435600,600.200012,0.359985,3.599854,True,91.300049,True
2021-07-14,608.140015,611.299988,604.010010,608.830017,608.830017,1376900,605.010010,3.130005,31.300049,True,62.899780,True
2021-07-15,608.400024,609.950012,602.650024,606.169983,606.169983,1618100,608.830017,-0.429993,-4.299927,True,11.199951,True
2021-07-16,608.710022,611.619995,603.659973,606.099976,606.099976,1249700,606.169983,2.540039,25.400391,True,54.500122,True
2021-07-19,602.750000,610.690002,598.140015,602.049988,602.049988,2046600,606.099976,-3.349976,-33.499756,True,45.900269,True
2021-07-20,605.390015,612.750000,598.479980,608.719971,608.719971,1675700,602.049988,3.340027,33.400269,True,107.000122,True
2021-07-21,605.719971,612.580017,603.320007,612.260010,612.260010,1381000,608.719971,-3.000000,-30.000000,True,38.600464,True
2021-07-22,614.580017,623.950012,614.580017,623.679993,623.679993,1477900,612.260010,2.320007,23.200073,True,116.900024,True
2021-07-23,625.760010,631.640015,622.000000,625.869995,625.869995,2030400,623.679993,2.080017,20.800171,True,79.600220,True
2021-07-26,624.179993,625.869995,619.729980,620.799988,620.799988,1389800,625.869995,-1.690002,-16.900024,False,0.000000,False
2021-07-27,621.000000,623.919983,610.640015,618.280029,618.280029,1540300,620.799988,0.200012,2.000122,True,31.199951,True
2021-07-28,620.989990,626.000000,617.570007,620.919983,620.919983,1468100,618.280029,2.709961,27.099609,True,77.199707,True
2021-07-29,617.039978,625.669983,617.039978,621.700012,621.700012,1068900,620.919983,-3.880005,-38.800049,True,47.500000,True
2021-07-30,619.030029,622.799988,617.289978,621.630005,621.630005,1403400,621.700012,-2.669983,-26.699829,True,10.999756,True
2021-08-02,625.869995,627.599976,612.929993,618.750000,618.750000,1466800,621.630005,4.239990,42.399902,True,59.699707,True
2021-08-03,620.229980,624.700012,614.000000,621.280029,621.280029,1067300,618.750000,1.479980,14.799805,True,59.500122,True
2021-08-04,622.469971,627.080017,617.619995,625.679993,625.679993,1306800,621.280029,1.189941,11.899414,True,57.999878,True
2021-08-05,626.989990,632.469971,623.000000,632.080017,632.080017,1158200,625.679993,1.309998,13.099976,True,67.899780,True
2021-08-06,629.270020,631.840027,625.169983,631.380005,631.380005,1127700,632.080017,-2.809998,-28.099976,False,-2.399902,False
2021-08-09,634.979980,634.979980,626.919983,629.219971,629.219971,1118900,631.380005,3.599976,35.999756,True,35.999756,True
2021-08-10,630.479980,633.299988,620.599976,621.739990,621.739990,1539700,629.219971,1.260010,12.600098,True,40.800171,True
2021-08-11,623.760010,627.419983,621.650024,626.030029,626.030029,1328300,621.739990,2.020020,20.200195,True,56.799927,True

In [349]:
df[['worked','Prof', 'best', 'actual']].tail(60)

            worked      Prof        best     actual
Date
2021-07-12   False       NaN         NaN        NaN
2021-07-13    True  0.359985   91.300049   3.599854
2021-07-14    True  3.130005   62.899780  31.300049
2021-07-15    True -0.429993   11.199951  -4.299927
2021-07-16    True  2.540039   54.500122  25.400391
2021-07-19    True -3.349976   45.900269 -33.499756
2021-07-20    True  3.340027  107.000122  33.400269
2021-07-21    True -3.000000   38.600464 -30.000000
2021-07-22    True  2.320007  116.900024  23.200073
2021-07-23    True  2.080017   79.600220  20.800171
2021-07-26   False -1.690002    0.000000 -16.900024
2021-07-27    True  0.200012   31.199951   2.000122
2021-07-28    True  2.709961   77.199707  27.099609
2021-07-29    True -3.880005   47.500000 -38.800049
2021-07-30    True -2.669983   10.999756 -26.699829
2021-08-02    True  4.239990   59.699707  42.399902
2021-08-03    True  1.479980   59.500122  14.799805
2021-08-04    True  1.189941   57.999878  11.899414
2021-08-05    True  1.309998   67.899780  13.099976
2021-08-06   False -2.809998   -2.399902 -28.099976
2021-08-09    True  3.599976   35.999756  35.999756
2021-08-10    True  1.260010   40.800171  12.600098
2021-08-11    True  2.020020   56.799927  20.200195

In [356]:
# summ = sum(df['actual'])
df['actual'].sum()

1151.099853515625

In [354]:
x = df.tail(1)['Close']
y = df.head(1)['Close']

In [355]:
x,y

(Date
 2021-08-11    626.030029
 Name: Close, dtype: float64,
 Date
 2021-07-12    600.200012
 Name: Close, dtype: float64)